### ISSUE TITLE
binaries don't work.

### ISSUE THREAD

**Issue by NinoM4ster** [bibo5088/mangadex-downloader#1]
it just says "stod"

**Comment by bibo5088** [comment]
Which OS are you using?
What manga are you trying to download?

The binaries are not up to date, I'll update them soon.

**Comment by bibo5088** [comment]
The new binaries are up. It took more time than expected, because I ran into some issues with cmake and MSVC.

**Comment by NinoM4ster** [comment]
Sorry, I didn't have enough time to reply during the day.

> Which OS are you using?
I tried on both Windows (10) and Linux (Ubuntu 18). 

> What manga are you trying to download?
None would work.

> The new binaries are up.
Thanks, I'll try it soon and inform you.

>It took more time than expected, because I ran into some issues with cmake and MSVC.
And that's why I avoid building stuff myself at all costs...  :)  it just never works.

**Comment by NinoM4ster** [comment]
Tested on Linux (Ubuntu 16) and it works like a charm  :)

(that being said, I had to [add a PPA](https://github.com/ponylang/ponyc/issues/1665#issuecomment-286232036) to install the correct version of libstdc++6 otherwise it wouldn't work so it was a bit time consuming.)
