### ISSUE TITLE
(suggestion) Add an option to download a specific chapter.

### ISSUE THREAD

**Issue by NinoM4ster** [bibo5088/mangadex-downloader#2]
Currently you can only download the entire manga, if I'm not mistaken. So it would be nice having the option to download a single chapter.

**Comment by bibo5088** [comment]
I added a new argument: `-c` (or `--chapter`). It's still possible to download every chapter by leaving it blank.

**Comment by NinoM4ster** [comment]
Awesome, but what exactly should I use as the chapter name?

The default format as shown on the website ("Vol. X Ch. YY")?

**Comment by bibo5088** [comment]
YY should be the chapter name. Just to be sure, you could check in the api `https://mangadex.org/api/manga/:id` the value of `"chapter"`.

**Comment by NinoM4ster** [comment]
I did *not* know they had an API. haha

I guess this also answers my question of "how the heck does he parse the images URLs?" (I tried building a similar script but failed)

Thanks!
